title: Victor Buttignon 
logo: /assets/img/headshot_profile.jpg
# description:  Pode colocar um texto embaixo da imagem
# show_downloads:
theme: jekyll-theme-minimal
defaults:
  - scope:
      path: ""
    values:
      layout: "default"